def submit():
    t2.delete(0,len(t2.get()))
    t3.delete(0,len(t3.get()))
    t4.delete(0,len(t4.get()))
    t5.delete(0,len(t5.get()))
    for i in t1.get():
        if i in 'aeiouAEIOU':
            t2.insert(len(t2.get()),i)
        else:
            if i.isdigit():
                t5.insert(len(t5.get()),i)
            elif i.isalpha():
                t3.insert(len(t3.get()),i)
            else:
                t4.insert(len(t4.get()),i)
    t22.delete(0,len(t22.get()))
    t22.insert(0,len(t2.get()))
    t33.delete(0,len(t33.get()))
    t33.insert(0,len(t3.get()))
    t44.delete(0,len(t44.get()))
    t44.insert(0,len(t4.get()))
    t55.delete(0,len(t55.get()))
    t55.insert(0,len(t5.get()))
def clr():
    t55.delete(0,len(t55.get()))
    t5.delete(0,len(t5.get()))
    t44.delete(0,len(t44.get()))
    t4.delete(0,len(t4.get()))
    t33.delete(0,len(t33.get()))
    t3.delete(0,len(t3.get()))
    t22.delete(0,len(t22.get()))
    t2.delete(0,len(t2.get()))
    t1.delete(0,len(t1.get()))
def back():
    t55.delete(0,len(t55.get()))
    t5.delete(0,len(t5.get()))
    t44.delete(0,len(t44.get()))
    t4.delete(0,len(t4.get()))
    t33.delete(0,len(t33.get()))
    t3.delete(0,len(t3.get()))
    t22.delete(0,len(t22.get()))
    t2.delete(0,len(t2.get()))
    s=t1.get()
    t1.delete(0,len(t1.get()))
    su=s[:len(s)-1]
    t1.insert(0,su)
from tkinter import *
w=Tk()
w.geometry('540x150')
w.configure(bg='light pink')
w.title("Dhanush's String Summarizer")
l1=Label(w,text='Enter Some String Here',bg='blue',fg='white')
l1.grid(row=0,column=0)
t1=Entry(w,width=30)
t1.grid(row=0,column=1)
bs=Button(w,text='Submit',bg='green',width=9,command=submit)
bs.grid(row=0,column=2)
bc=Button(w,text='Clear',bg='red',width=9,command=clr)
bc.grid(row=0,column=3)
bb=Button(w,text='<|--',bg='orange',width=9,command=back)
bb.grid(row=0,column=4)
t2=Entry(w,width=30)
t2.grid(row=2,column=1)
l2=Label(w,text="Vowel's Description",bg='light blue',width=18)
l2.grid(row=2,column=0)
num=Label(w,text='Characters',width=20,bg='lime')
num.grid(row=1,column=1)
lt=Label(w,text='Number Of Characters',width=20,bg='lime')
lt.grid(row=1,column=2,columnspan=3)
t22=Entry(w,width=35)
t22.grid(row=2,column=2,columnspan=3)
l3=Label(w,text="Consonent's Description",bg='light yellow',width=18)
l3.grid(row=3,column=0)
t3=Entry(w,width=30)
t3.grid(row=3,column=1)
t33=Entry(w,width=35)
t33.grid(row=3,column=2,columnspan=3)
l4=Label(w,text="Symbol's Description",bg='light blue',width=18)
l4.grid(row=4,column=0)
t4=Entry(w,width=30)
t4.grid(row=4,column=1)
t44=Entry(w,width=35)
t44.grid(row=4,column=2,columnspan=3)
l5=Label(w,text="Digit's Description",bg='light yellow',width=18)
l5.grid(row=5,column=0)
t5=Entry(w,width=30)
t5.grid(row=5,column=1)
t55=Entry(w,width=35)
t55.grid(row=5,column=2,columnspan=3)
